export const CHANGE_SETTINGS_REQUEST = "CHANGE_OTHER_DETAILS_REQUEST";
export const CHANGE_SETTINGS_SUCCESS = "CHANGE_OTHER_DETAILS_SUCCESS";
export const CHANGE_SETTINGS_FAILURE = "CHANGE_OTHER_DETAILS_FAILURE";
