export const ADD_TEAM_REQUEST = "ADD_TEAM_REQUEST";
export const ADD_TEAM_SUCCESS = "ADD_TEAM_SUCCESS";
export const ADD_TEAM_FAILURE = "ADD_TEAM_FAILURE";


export const UPDATE_CURRENT_TEAM_REQUEST = "UPDATE_CURRENT_TEAM_REQUEST";
export const UPDATE_CURRENT_TEAM_SUCCESS = "UPDATE_CURRENT_TEAM_SUCCESS";
export const UPDATE_CURRENT_TEAM_FAILURE = "UPDATE_CURRENT_TEAM_FAILURE";

export const ADD_MEMBERS_TO_TEAM_REQUEST = "ADD_MEMBERS_TO_TEAM_REQUEST";
export const ADD_MEMBERS_TO_TEAM_SUCCESS = "ADD_MEMBERS_TO_TEAM_SUCCESS";
export const ADD_MEMBERS_TO_TEAM_FAILURE = "ADD_MEMBERS_TO_TEAM_FAILURE";