export const ADD_TEAM_REQUEST = "ADD_TEAM_REQUEST";
export const ADD_TEAM_SUCCESS = "ADD_TEAM_SUCCESS";
export const ADD_TEAM_FAILURE = "ADD_TEAM_FAILURE";

export const FETCH_TEAM_REQUEST = "FETCH_TEAM_REQUEST";
export const FETCH_TEAM_SUCCESS = "FETCH_TEAM_SUCCESS";
export const FETCH_TEAM_FAILURE = "FETCH_TEAM_FAILURE";

export const ADD_MEMBERS_TO_TEAM_REQUEST = "ADD_MEMBERS_TO_TEAM_REQUEST";
export const ADD_MEMBERS_TO_TEAM_SUCCESS = "ADD_MEMBERS_TO_TEAM_SUCCESS";
export const ADD_MEMBERS_TO_TEAM_FAILURE = "ADD_MEMBERS_TO_TEAM_FAILURE";

export const MAKE_TEAM_LEADER_REQUEST = "MAKE_TEAM_LEADER_REQUEST";
export const MAKE_TEAM_LEADER_SUCCESS = "MAKE_TEAM_LEADER_SUCCESS";
export const MAKE_TEAM_LEADER_FAILURE = "MAKE_TEAM_LEADER_FAILURE";

export const UDPATE_TEAM_DETAILS_REQUEST = "UDPATE_TEAM_DETAILS_REQUEST";
export const UDPATE_TEAM_DETAILS_SUCCESS = "UDPATE_TEAM_DETAILS_SUCCESS";
export const UDPATE_TEAM_DETAILS_FAILURE = "UDPATE_TEAM_DETAILS_FAILURE";

export const DELETE_TEAM_REQUEST = "DELETE_TEAM_REQUEST";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_FAILURE = "DELETE_TEAM_FAILURE";