export const ADD_TEAM_REQUEST = "ADD_TEAM_REQUEST";
export const ADD_TEAM_SUCCESS = "ADD_TEAM_SUCCESS";
export const ADD_TEAM_FAILURE = "ADD_TEAM_FAILURE";


export const FETCH_TEAM_REQUEST = "FETCH_TEAM_REQUEST";
export const FETCH_TEAM_SUCCESS = "FETCH_TEAM_SUCCESS";
export const FETCH_TEAM_FAILURE = "FETCH_TEAM_FAILURE";

export const ADD_MEMBERS_TO_TEAM_REQUEST = "ADD_MEMBERS_TO_TEAM_REQUEST";
export const ADD_MEMBERS_TO_TEAM_SUCCESS = "ADD_MEMBERS_TO_TEAM_SUCCESS";
export const ADD_MEMBERS_TO_TEAM_FAILURE = "ADD_MEMBERS_TO_TEAM_FAILURE";