export const ADD_WORKSPACE_REQUEST = "ADD_WORKSPACE_REQUEST";
export const ADD_WORKSPACE_SUCCESS = "ADD_WORKSPACE_SUCCESS";
export const ADD_WORKSPACE_FAILURE = "ADD_WORKSPACE_FAILURE";

export const DELETE_WORKSPACE_REQUEST = "DELETE_WORKSPACE_REQUEST";
export const DELETE_WORKSPACE_SUCCESS = "DELETE_WORKSPACE_SUCCESS";
export const DELETE_WORKSPACE_FAILURE = "DELETE_WORKSPACE_FAILURE";

export const FETCH_WORKSPACE_REQUEST = "FETCH_WORKSPACE_REQUEST";
export const FETCH_WORKSPACE_SUCCESS = "FETCH_WORKSPACE_SUCCESS";
export const FETCH_WORKSPACE_FAILURE = "FETCH_WORKSPACE_FAILURE";

export const ADD_MEMBERS_TO_WORKSPACE_REQUEST = "ADD_MEMBERS_TO_WORKSPACE_REQUEST";
export const ADD_MEMBERS_TO_WORKSPACE_SUCCESS = "ADD_MEMBERS_TO_WORKSPACE_SUCCESS";
export const ADD_MEMBERS_TO_WORKSPACE_FAILURE = "ADD_MEMBERS_TO_WORKSPACE_FAILURE";